# Använd H2 som in-memory databas
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (så att du kan titta på databasen i webbläsaren)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate och SQL-initiering enligt lärarens tips
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/auth/jwks

spring.sql.init.mode=always